---
title: "main"
author: "Yevhenii Romanenko"
date: "4/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Set all required libraries and download data
```{r}
set.seed(20162)
library(knitr)
library(lattice)
library(ggplot2)
library(caret)
library(rpart)
library(rpart.plot)
library(corrplot)
library(RColorBrewer)
library(rattle)
library(randomForest)
library(data.table)
library(corrplot)
library(plotly)
library(gbm)

trainData <- read.csv("data/pml-training.csv")
verificationData <- read.csv("data/pml-testing.csv")
dim(trainData)
```

Separate data to training and test sets
```{r}
inTrain <- createDataPartition(trainData$classe, p=0.7, list = FALSE)

trainSet <- trainData[inTrain, ]
testSet <- trainData[-inTrain, ]
```

Preprocess sets and check correlation
```{r}
nzValues <- nearZeroVar(trainSet)

trainSet <- trainSet[ , -nzValues]
testSet  <- testSet [ , -nzValues]

naValue <- sapply(trainSet, function(x) mean(is.na(x))) > 0.95

trainSet <- trainSet[ , naValue == FALSE]
testSet  <- testSet [ , naValue == FALSE]

#Since columns 1 to 5, it are identificators
trainSet <- trainSet[ , -(1:5)]
testSet  <- testSet [ , -(1:5)]

classeIndex <- 54
names(trainSet)[classeIndex]

corrMatrix <- cor(trainSet[ , -classeIndex])
corrplot(corrMatrix, order = "FPC", method = "circle", type = "lower",
         tl.cex = 0.6, tl.col = rgb(0, 0, 0))
```

Fit and test Decision Tree model
```{r}
set.seed(20162)

fitModelDT <- rpart(classe~., data=trainSet, method="class")

predictDT <- predict(fitModelDT, newdata=testSet, type="class")

confMatrixDT <- confusionMatrix(table(predictDT, testSet$classe))
confMatrixDT
```

Fit and test GBM model
```{r}
set.seed(20162)

ctrlGBM <- trainControl(method = "repeatedcv", number = 5, repeats = 2)
fitModelGBM <- train(classe~., data=trainSet, method="gbm", trControl=ctrlGBM, verbose=FALSE)
fitModelGBM$finalModel

predictGBM <- predict(fitModelGBM, newdata=testSet)

confMatrixGBM <- confusionMatrix(table(predictGBM, testSet$classe))
confMatrixGBM
```

Fit and test Random Forest model
```{r}
set.seed(20162)

ctrlRF <- trainControl(method = "repeatedcv", number = 5, repeats = 2)
fitModelRF <- train(classe~., data=trainSet, method="rf", trControl=ctrlRF, verbose=FALSE)
fitModelRF$finalModel

predictRF <- predict(fitModelRF, newdata=testSet)
confMatrixRF <- confusionMatrix(table(predictRF, testSet$classe))
confMatrixRF
```

Decision Tree Model: 73 % Generalized Boosted Model: 98.81 % Random Forest Model: 99.83 %
According to results Randow Forest model is selected
```{r}
cat("Predictions: ", paste(predict(fitModelRF, verificationData)))
```

